name: on merging to default branch

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jq
        run: yarn add jq
          
      - name: get version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"') 
          echo "::set-output name=PACKAGE_VERSION::$(cat ./package.json | jq '.version' | tr -d '"')"
          echo $PACKAGE_VERSION
        id: version

      - name: Build
        run: |
          yarn run all

      - name: bump-version
        id: bump_version
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}
          DELETE_BRANCH: false
          CHANGELOG_PATH: ./CHANGELOG.md
          PACKAGE_JSON_PATH: ./package.json
      - name: update develop branch
        run: |
          git add package.json
          git add CHANGELOG.md
          git add dist
          git commit -m "Skip CI"
          git push